version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - errorlint
    - gocritic
    - gosec
    - importas
    - misspell
    - revive
    - staticcheck
    - testifylint
    - unconvert
  settings:
    depguard:
      rules:
        Main:
          deny:
            - pkg: github.com/gogo/protobuf
              desc: gogo/protobuf is deprecated, use golang/protobuf
            - pkg: gopkg.in/yaml.v2
              desc: use sigs.k8s.io/yaml instead
            - pkg: gopkg.in/yaml.v3
              desc: use sigs.k8s.io/yaml instead
            - pkg: k8s.io/utils/pointer
              desc: use k8s.io/utils/ptr instead
    govet:
      disable:
        - fieldalignment
      enable-all: true
    importas:
      alias:
        - pkg: sigs.k8s.io/gateway-api/apis/v1
          alias: gwapiv1
        - pkg: sigs.k8s.io/gateway-api/apis/v1alpha2
          alias: gwapiv1a2
        - pkg: sigs.k8s.io/gateway-api/apis/v1alpha3
          alias: gwapiv1a3
        - pkg: sigs.k8s.io/gateway-api/apis/v1beta1
          alias: gwapiv1b1
        - pkg: github.com/envoyproxy/gateway/api/v1alpha1
          alias: egv1a1
        - pkg: github.com/envoyproxy/ai-gateway/api/v1alpha1
          alias: aigv1a1
        - pkg: sigs.k8s.io/gateway-api-inference-extension/api/v1alpha2
          alias: gwaiev1a2
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
          alias: apiextensionsv1
        - pkg: sigs.k8s.io/mcs-api/pkg/apis/v1alpha1
          alias: mcsapiv1a1
        - pkg: k8s.io/api/(\w+)/(v[\w\d]+)
          alias: $1$2
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: github.com/envoyproxy/ai-gateway/internal/testing
          alias: internaltesting
        - pkg: github.com/envoyproxy/go-control-plane/envoy/config/cluster/v3
          alias: clusterv3
        - pkg: github.com/envoyproxy/go-control-plane/envoy/config/route/v3
          alias: routev3
        - pkg: github.com/envoyproxy/gateway/proto/extension
          alias: egextension
        - pkg: github.com/envoyproxy/go-control-plane/envoy/extensions/filters/network/http_connection_manager/v3
          alias: httpconnectionmanagerv3
      no-unaliased: true
      no-extra-aliases: false
    testifylint:
      enable:
        - bool-compare
        - compares
        - empty
        - error-is-as
        - error-nil
        - expected-actual
        - len
        - require-error
        - suite-dont-use-pkg
        - suite-extra-assert-call
      disable:
        - float-compare
        - go-require
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - godot
        path: api
      - linters:
          - staticcheck
        text: 'SA1019:'
      - linters:
          - bodyclose
        path: test/e2e
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/envoyproxy/ai-gateway)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - zz_generated
