// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ModelPricingLister helps list ModelPricings.
// All objects returned here must be treated as read-only.
type ModelPricingLister interface {
	// List lists all ModelPricings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.ModelPricing, err error)
	// ModelPricings returns an object that can list and get ModelPricings.
	ModelPricings(namespace string) ModelPricingNamespaceLister
	ModelPricingListerExpansion
}

// modelPricingLister implements the ModelPricingLister interface.
type modelPricingLister struct {
	listers.ResourceIndexer[*apiv1alpha1.ModelPricing]
}

// NewModelPricingLister returns a new ModelPricingLister.
func NewModelPricingLister(indexer cache.Indexer) ModelPricingLister {
	return &modelPricingLister{listers.New[*apiv1alpha1.ModelPricing](indexer, apiv1alpha1.Resource("modelpricing"))}
}

// ModelPricings returns an object that can list and get ModelPricings.
func (s *modelPricingLister) ModelPricings(namespace string) ModelPricingNamespaceLister {
	return modelPricingNamespaceLister{listers.NewNamespaced[*apiv1alpha1.ModelPricing](s.ResourceIndexer, namespace)}
}

// ModelPricingNamespaceLister helps list and get ModelPricings.
// All objects returned here must be treated as read-only.
type ModelPricingNamespaceLister interface {
	// List lists all ModelPricings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.ModelPricing, err error)
	// Get retrieves the ModelPricing from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.ModelPricing, error)
	ModelPricingNamespaceListerExpansion
}

// modelPricingNamespaceLister implements the ModelPricingNamespaceLister
// interface.
type modelPricingNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.ModelPricing]
}
