// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1"
	scheme "github.com/envoyproxy/ai-gateway/api/v1alpha1/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ModelPricingsGetter has a method to return a ModelPricingInterface.
// A group's client should implement this interface.
type ModelPricingsGetter interface {
	ModelPricings(namespace string) ModelPricingInterface
}

// ModelPricingInterface has methods to work with ModelPricing resources.
type ModelPricingInterface interface {
	Create(ctx context.Context, modelPricing *apiv1alpha1.ModelPricing, opts v1.CreateOptions) (*apiv1alpha1.ModelPricing, error)
	Update(ctx context.Context, modelPricing *apiv1alpha1.ModelPricing, opts v1.UpdateOptions) (*apiv1alpha1.ModelPricing, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, modelPricing *apiv1alpha1.ModelPricing, opts v1.UpdateOptions) (*apiv1alpha1.ModelPricing, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.ModelPricing, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.ModelPricingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.ModelPricing, err error)
	ModelPricingExpansion
}

// modelPricings implements ModelPricingInterface
type modelPricings struct {
	*gentype.ClientWithList[*apiv1alpha1.ModelPricing, *apiv1alpha1.ModelPricingList]
}

// newModelPricings returns a ModelPricings
func newModelPricings(c *AigatewayV1alpha1Client, namespace string) *modelPricings {
	return &modelPricings{
		gentype.NewClientWithList[*apiv1alpha1.ModelPricing, *apiv1alpha1.ModelPricingList](
			"modelpricings",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.ModelPricing { return &apiv1alpha1.ModelPricing{} },
			func() *apiv1alpha1.ModelPricingList { return &apiv1alpha1.ModelPricingList{} },
		),
	}
}
