// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1"
	apiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeModelPricings implements ModelPricingInterface
type fakeModelPricings struct {
	*gentype.FakeClientWithList[*v1alpha1.ModelPricing, *v1alpha1.ModelPricingList]
	Fake *FakeAigatewayV1alpha1
}

func newFakeModelPricings(fake *FakeAigatewayV1alpha1, namespace string) apiv1alpha1.ModelPricingInterface {
	return &fakeModelPricings{
		gentype.NewFakeClientWithList[*v1alpha1.ModelPricing, *v1alpha1.ModelPricingList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("modelpricings"),
			v1alpha1.SchemeGroupVersion.WithKind("ModelPricing"),
			func() *v1alpha1.ModelPricing { return &v1alpha1.ModelPricing{} },
			func() *v1alpha1.ModelPricingList { return &v1alpha1.ModelPricingList{} },
			func(dst, src *v1alpha1.ModelPricingList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ModelPricingList) []*v1alpha1.ModelPricing {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ModelPricingList, items []*v1alpha1.ModelPricing) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
